app <- ShinyDriver$new("../../")
app$snapshotInit("JoesFlow_snapshot_test")

timeout <- 2e4

app$setInputs(nav_bar = "Visualize", timeout_=timeout)
app$executeScript("$('.modal').modal('hide');")
app$snapshot()
app$setInputs(main_output = "PCA", timeout_=timeout)
app$snapshot()
app$setInputs(show_hide_dimreduct_legend = "Hide")
app$setInputs(show_hide_cluster_legend = "Hide")
app$snapshot()
app$setInputs(main_output = "UMAP", timeout_=timeout)
app$snapshot()
app$setInputs(main_output = "TSNE", timeout_=timeout)
app$snapshot()
app$setInputs(main_output = "Composition", timeout_=timeout)
# Input 'plot1_brush' was set, but doesn't have an input binding.
app$snapshot()
app$setInputs(feat_dim = "PCA", timeout_=timeout)
app$snapshot()
app$setInputs(main_output = "Markers", timeout_=timeout)
app$snapshot()
app$setInputs(kmean = 6)
app$snapshot()
app$setInputs(main_output = "Composition", timeout_=timeout)
app$snapshot()
app$setInputs(meta_val = "Group", timeout_=timeout)
app$snapshot()
app$setInputs(main_output = "PCA", timeout_=timeout)
app$snapshot()
app$setInputs(clust_type = "Hierarchical", timeout_=timeout)
app$snapshot()
